#!/usr/bin/env bash

# This will require to be executed on an elevated sudo level user

JDK=$1


echo "Requested JDK is $JDK"

case $JDK in
	(9)
		rm /opt/java/current
		ln -s /opt/java/jdk-9.0.1 /opt/java/current
		;;
	(*)
  		rm /opt/java/current
		ln -s /opt/java/jdk1.8.0_151 /opt/java/current
  		;;
esac

java -version
javac -version
