#!/usr/bin/env bash

pdfmerge() {
	gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -sOutputFile=$@ ; 
}

if [ $# -eq 0 ]
  then
    	echo "Usage: $0 merged.pdf mine1.pdf mine2.pdf"
	else
		pdfmerge $*
fi



