#!/bin/bash


FILE=$1

TARGET=/tmp/Music

if [ ! -f "$FILE" ]
then
    echo "File $FILE does not exist"
    exit 1
fi

FILEDIR=$(dirname "$FILE")
TMP=$(basename "$FILE")
NAME="${TMP%%.*}"

echo "FILE= $FILE"
echo "FILEDIR= $FILEDIR"
echo "NAME= \"$NAME\""

cd $FILEDIR
pwd

if [ -d "$TARGET/$NAME" ]; then
   rm -rf "$TARGET/$NAME"
fi

mkdir -p "$TARGET/$NAME"
echo "Target: $TARGET/$NAME"



cat "$FILE" | grep File | awk -F= '{printf $2 "\n"}'>/tmp/TO_COPY
TOTAL_FILES=$(cat /tmp/TO_COPY | wc -l )
echo "Total Files to copy $TOTAL_FILES"
while read fileToCopy; do
  echo "Copying $FILEDIR/$fileToCopy => $TARGET/$NAME";
  cp "$FILEDIR/$fileToCopy" "$TARGET/$NAME";
done </tmp/TO_COPY



FOLDER="$TARGET/$NAME"
DEST="/tmp/Car_Songs"

echo "changing dir to $FOLDER"
cd "$FOLDER"
echo "Working on"
pwd


for f in *.mp3; do
    name=`echo "$f"|sed 's/ -.*//'`
    # echo "Edit Tags for $f as \"$name\""
    /usr/bin/mid3v2 -D "$f"
    /usr/bin/mid3v2 -v --TIT3 "$name" "$f"
    letter=`echo "$name"|cut -c1`
    lowercase="$(tr [A-Z] [a-z] <<< "$letter")"
    dir="$DEST/$lowercase"
    mkdir -p "$dir"
    mv "$f" "$dir"
done
